# Generated by Django 4.0.4 on 2022-06-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
    ]
