# Generated by Django 4.0.4 on 2022-06-07 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_upload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Text',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
